#!/usr/bin/env python3
"""
generate_health.py — regenerate static/api/health.json for uutistenlukija.fi

Outputs a static JSON file served at https://uutistenlukija.fi/api/health.json

Fields:
  status         "ok" | "degraded"  (degraded if lastPublished > 6h ago or 0 articles)
  lastPublished  ISO8601 UTC timestamp of most recently published article (or null)
  articleCount   total .md files in content/posts/
  generatedAt    ISO8601 UTC timestamp of this file generation
  uptimeCheck    always true when generated by pipeline (site was just built)
  pipeline       { lastRun, successRate7d, publishedToday }

Called by pipeline/auto_publish.sh after each successful build.
"""

import json
import re
import sys
from datetime import datetime, timezone, timedelta
from pathlib import Path

# ── Paths ─────────────────────────────────────────────────────────────────────
SCRIPT_DIR  = Path(__file__).parent          # pipeline/
PROJECT_DIR = SCRIPT_DIR.parent
CONTENT_DIR = PROJECT_DIR / "content" / "posts"
METRICS_FILE = SCRIPT_DIR / "logs" / "metrics.json"
PUBLISH_METRICS = SCRIPT_DIR / "logs" / "publish-metrics.json"
OUT_FILE    = PROJECT_DIR / "static" / "api" / "health.json"

STALE_THRESHOLD_HOURS = 6


def latest_article_timestamp() -> tuple[str | None, int]:
    """Scan content/posts/ for the most recent publish date. Returns (iso_ts, count)."""
    if not CONTENT_DIR.exists():
        return None, 0

    articles = list(CONTENT_DIR.glob("**/*.md"))
    count = len(articles)
    if not articles:
        return None, 0

    latest_dt: datetime | None = None
    date_re = re.compile(r'^date\s*=\s*["\']?(\d{4}-\d{2}-\d{2}[T ]\d{2}:\d{2}:\d{2}[^"\']*)["\']?', re.MULTILINE)

    for article in articles:
        try:
            text = article.read_text(encoding="utf-8", errors="ignore")
            m = date_re.search(text)
            if not m:
                continue
            raw = m.group(1).strip()
            # normalise: replace space with T, ensure UTC
            raw = raw.replace(" ", "T")
            if not raw.endswith("Z") and "+" not in raw[10:] and "-" not in raw[10:]:
                raw += "Z"
            dt = datetime.fromisoformat(raw.replace("Z", "+00:00"))
            if latest_dt is None or dt > latest_dt:
                latest_dt = dt
        except Exception:
            continue

    if latest_dt is None:
        # fallback: use mtime of newest file
        newest = max(articles, key=lambda p: p.stat().st_mtime)
        latest_dt = datetime.fromtimestamp(newest.stat().st_mtime, tz=timezone.utc)

    return latest_dt.strftime("%Y-%m-%dT%H:%M:%SZ"), count


def pipeline_stats() -> dict:
    """Read metrics files for pipeline summary."""
    last_run = None
    success_rate_7d = None
    published_today = 0

    # From metrics.json (per-run records)
    if METRICS_FILE.exists():
        try:
            runs = json.loads(METRICS_FILE.read_text())
            if isinstance(runs, list) and runs:
                last = runs[-1]
                last_run = last.get("timestamp")

                # 7-day success rate
                cutoff = datetime.now(timezone.utc) - timedelta(days=7)
                recent = []
                for r in runs:
                    try:
                        ts = datetime.fromisoformat(r["timestamp"].replace("Z", "+00:00"))
                        if ts >= cutoff:
                            recent.append(r)
                    except Exception:
                        pass
                if recent:
                    success_rate_7d = round(
                        100 * sum(1 for r in recent if r.get("success")) / len(recent), 1
                    )
        except Exception:
            pass

    # Published today from publish-metrics.json
    if PUBLISH_METRICS.exists():
        today_str = datetime.now(timezone.utc).strftime("%Y-%m-%d")
        try:
            for line in PUBLISH_METRICS.read_text().splitlines():
                line = line.strip()
                if not line:
                    continue
                rec = json.loads(line)
                ts = rec.get("ts", "")
                try:
                    dt = datetime.fromisoformat(ts.replace("Z", "+00:00"))
                    if dt.strftime("%Y-%m-%d") == today_str:
                        published_today += rec.get("published", 0)
                except Exception:
                    pass
        except Exception:
            pass

    return {
        "lastRun": last_run,
        "successRate7d": success_rate_7d,
        "publishedToday": published_today,
    }


def main():
    now = datetime.now(timezone.utc)
    last_published, article_count = latest_article_timestamp()

    # Determine status
    status = "ok"
    if article_count == 0:
        status = "degraded"
    elif last_published:
        try:
            lp_dt = datetime.fromisoformat(last_published.replace("Z", "+00:00"))
            age_hours = (now - lp_dt).total_seconds() / 3600
            if age_hours > STALE_THRESHOLD_HOURS:
                status = "degraded"
        except Exception:
            pass

    health = {
        "status": status,
        "lastPublished": last_published,
        "articleCount": article_count,
        "generatedAt": now.strftime("%Y-%m-%dT%H:%M:%SZ"),
        "uptimeCheck": True,   # always true when generated — site was just built
        "pipeline": pipeline_stats(),
    }

    OUT_FILE.parent.mkdir(parents=True, exist_ok=True)
    OUT_FILE.write_text(json.dumps(health, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    print(f"[generate_health] Written to {OUT_FILE}")
    print(f"[generate_health] status={status}  articles={article_count}  lastPublished={last_published}")

    return 0


if __name__ == "__main__":
    sys.exit(main())
